### ISSUE TITLE
Relax checking for database

### ISSUE THREAD

**Issue by rclai** [emgee3/meteor-mssql#1]
Can you remove this [check](https://github.com/emgee3/meteor-mssql/blob/master/mssql.js#L10)?

I'm trying to query between multiple databases in the same connection.

**Comment by emgee3** [comment]
I'll have to test but I'm pretty sure you need a default database, even if you're querying cross database.

**Comment by emgee3** [comment]
After thorough testing and verification (read as "tried once in one app") I have determined that you indeed do not need a default database.

The check has therefor been removed, and I have published a new version.

**Comment by rclai** [comment]
Cool, thanks.
