### ISSUE TITLE
PS keeps creating new connections, not getting unprepared 

### ISSUE THREAD

**Issue by batjko** [emgee3/meteor-mssql#14]
Ok, so I am using the sync-style code from the README, and also unprepare after every call of the prepared statement.
And yet, SQL Server keeps these connections alive and stops creating new ones after 10:

The following code is run by a Meteor method, every time I click a button on the front end:

``` js
      let opts = {
        query: "SELECT * from MyTable"
      }

      try {
        query = Sql.ps(opts);
      } catch (e) {
        throw new Meteor.Error(e);
      }

      let result  = query({});
      query.unprepare();
```

And after clicking a few times, this is what SQL Server activity Monitor shows:
![image](https://cloud.githubusercontent.com/assets/7287076/11325908/2b990dd6-9152-11e5-9655-8b18765129ca.png)

Have I forgotten to do something, that allows the extra connections to be closed down again?

**Comment by paarmstrong** [comment]
I don't know if you have found the cause of this issue yet, but I ran into something similar.

It seems that you are creating a new prepared statement each time the user clicks the button. This also creates a new connection.

Instead, you should declare the prepared statement somewhere which is only going to be called one, and is accessible to your click function, and then simply call your prepared statement from inside your click function as usual.

**Comment by batjko** [comment]
@paarmstrong I haven't solved it, no. I understand what you're saying, but I'm not sure how to do it. 
Do I need to create all possible prepared statements at application launch, and then only execute them whenever I need them?

**Comment by emgee3** [comment]
Sorry for not responding earlier. I haven't really spent any development time on this recently because when Meteor 1.3 comes out, we'll no longer need a wrapper and can use the node driver directly.

That said, if someone comes up with a fix for this that is backward compatible, I'll certainly merge and publish it. But I don't foresee myself doing any more development on it.

**Comment by batjko** [comment]
That makes sense. I haven't done anything with this package for a while either, as I decided to use Sequelize at the time. I have yet to try it with the 1.3 beta, but that switch back to standard npm shouldn't be difficult.
