### ISSUE TITLE
The connection do not release 

### ISSUE THREAD

**Issue by hungchai** [emgee3/meteor-mssql#17]
I created a meteor.methods to select data from mssql, and I added [pool] option to the settings.json.

```
"pool": {
            "max": 50,
            "min": 0,
            "idleTimeoutMillis": 3000
        }
```

But I found that, after the connection met 50, the Sql.ps will return null; 
how to solve this problem?

**Comment by emgee3** [comment]
Not sure, never ran it to this. You might try looking at the underlying node driver https://github.com/patriksimek/node-mssql (note this uses an older version of node-mssql).

**Comment by hungchai** [comment]
thanks
