### ISSUE TITLE
Displaying data

### ISSUE THREAD

**Issue by DanceParty** [emgee3/meteor-mssql#19]
Im curious as to how to go about displaying data from the SQL database on the client side in a form.

Thanks!

**Comment by DanceParty** [comment]
To follow up on this, in order to display it to the client, do I need to be moving the data from the SQL database to the mongodb collections? or can you wrap the mssql in a publish method?

**Comment by emgee3** [comment]
I personally don't bother using mongodb collections for data coming from MSSQL. I deliver the query results to the client using a Meteor method.

**Comment by DanceParty** [comment]
I guess I am confused as to how to actually display the information? Currently I can write information written on the client to the MSSQL database but I don't know how to display information from the MSSQL db to the client so that's what I have been trying to learn through collections, but no luck so far.

**Comment by emgee3** [comment]
Probably the easiest is storing the results in a [ReactiveVar](http://docs.meteor.com/api/reactive-var.html).
