### ISSUE TITLE
Using Insert statements?

### ISSUE THREAD

**Issue by batjko** [emgee3/meteor-mssql#9]
Hi there,

How do I insert data with this package?

I am now able to execute a prepared statement, querying for data, also with parameters etc, and that's great.

But when I try to do the same with an insert or update statement (in other words, any DML command), I get `RequestError: Statement(s) could not be prepared.`, without any further explanation.

For example:

``` javascript
var insertOpts = {
     query : "insert into Table_1 values ('@name', @age, @createdDate, @amount, @comment)",
     inputs : {
       name: Sql.driver.NVarChar,
       age: Sql.driver.Int,
       created: Sql.driver.DateTime2,
       amount: Sql.driver.Decimal,
       comment: Sql.driver.NVarChar
     }
   };

var newRow = {
      name: "Hippie",
      age: 25,
      created: new Date(),
      amount: 1000000.01,
      comment: "Inserted by Meteor"
    }

try {
   var insertRow = Sql.ps(insertOpts);
   var result2 = insertRow(newRow);

   console.log(JSON.stringify(result2));

   insertRow.unprepare();
 }
 catch (e) {
   throw new Meteor.Error(e);
 }


```

Is this not supposed to work?

**Comment by yanxiaoyan** [comment]
Hi there,
I am a learner,
【meteor.settings】Should be how to set it?

**Comment by batjko** [comment]
@yanxiaoyan You create a `settings.json` in your project folder, with the settings object inside. 
Then you start meteor with this parameter: `meteor --settings settings.json`

**Comment by emgee3** [comment]
@batjko It should definitely work. Can you trying something? On your insert query, try removing the single quotes around `@name` — the driver automatically handles the quoting and escaping for you.

If that doesn't do it, I'll dig into the code a bit.

**Comment by batjko** [comment]
Ah, good point.
I don't know why I have quotes around `@name` but not `@comment`, anyway.

I'll play with that, thanks for the tip.

**Comment by yanxiaoyan** [comment]
@batjko I created a settings.json in my project, but the file was not found.
  While preparing to run:
  settings.json:file not found <serttings file>

**Comment by batjko** [comment]
Sorry I left this open for so long.
I figured it out eventually.
Cheers.

**Comment by DanceParty** [comment]
How did you figure this out?

**Comment by batjko** [comment]
@jkd65 I'm sorry I don't recall actually, it's been a long time. I think in the end I may have used a Transaction instead of just a prepared statement?

Either way, I have since transitioned to using Sequelize for this kind of stuff.

**Comment by DanceParty** [comment]
@batjko does that work with Meteor?

**Comment by batjko** [comment]
Sequelize? It works with anything on Node, so you can use it in your server-side code in your Meteor app. (Of course it doesn't replace Meteor's Mongo right now, for that look at their Apollo project, which will eventually do that).

**Comment by DanceParty** [comment]
How about displaying data from the mssql server to the client? with either mssql or sequelize?

**Comment by batjko** [comment]
In Meteor you will still need to do this via Collections. On the server you use either mssql or sequelize to retrieve the data you need, put it into a collection, which you publish to the client, where you subscribe to it in order to display it on the client.

Like I said, none of these libraries replace the way Meteor currently sends data to the client.

**Comment by DanceParty** [comment]
I guess I am stuck inserting into the collections, I think I have everything else down. Any suggestions on where to learn this?

I appreciate your quick and helpful responses btw!

**Comment by batjko** [comment]
The official documentation really. For Meteor collections, the all-knowing [guide](http://guide.meteor.com/collections.html#server-collections) will help you long time. 

If you're using this mssql package to retrieve data, or sequelize (which takes some more reading), just retrieve data into some array by whatever method you want. Then you iterate over that array, and for each item you create a mongoDB object that you can insert into your collection.

If all fails, open a thread on the [meteor forum](https://forums.meteor.com/).
